# Generated by Django 3.1.3 on 2020-11-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentintopic',
            old_name='person',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='documentintopic',
            old_name='group',
            new_name='topic',
        ),
    ]
