# Generated by Django 3.1.3 on 2020-11-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201109_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='data',
            new_name='date',
        ),
    ]
