# Generated by Django 3.1.3 on 2020-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_originaltopicprobabilities_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='documents',
            field=models.ManyToManyField(through='core.DocumentInTopic', to='core.Document'),
        ),
    ]
