# Generated by Django 3.1.3 on 2020-11-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_topic_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('tweet', 'Twitter'), ('webpage', 'Webpage'), ('preprint', 'Preprint'), ('news', 'News'), ('youtube', 'YouTube'), ('report', 'Report'), ('blog', 'Blog')], default='blog', max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='doi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
