# Generated by Django 3.1.3 on 2020-11-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doi',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
