# Generated by Django 3.1.3 on 2020-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201110_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doi',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
