# Generated by Django 3.1.3 on 2020-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201110_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='documents',
            field=models.ManyToManyField(related_name='topics', through='core.DocumentInTopic', to='core.Document'),
        ),
    ]
