# Generated by Django 3.1.3 on 2020-11-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201116_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='active',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='active_topic_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topicmodel'),
        ),
    ]
